### PR TITLE
Feat: add per browser options

### PR DESCRIPTION
**Pull request by HugoPoi**
Make a proposal for solving #118 

* This is not a perfect solution
* I'm not a typescript guy not sure about the `LaunchOptions[] | undefined`

### CODE REVIEW

**Comment by ejames17** [comment]
is there a way i could pull those changes without forking @HugoPoi  ?

**Comment by HugoPoi** [comment]
You can use this in place of my PR : https://github.com/NikolaiT/se-scraper/blob/master/src/concurrency-implementation.js

https://github.com/NikolaiT/se-scraper/blob/master/src/node_scraper.js#L279-L287

**Comment by thomasdondorf** [comment]
Sorry for not looking into this earlier... I hope I have some time at the weekend to take a look.

And thanks for making a pull request.

**Comment by ejames17** [comment]
@thomasdondorf  @HugoPoi  thanks for this. Just starred this awesome repo  wish github had a tip jar.

**Comment by Legym** [comment]
This PR would be a great feature to have!

**Comment by thomasdondorf** [comment]
Sorry for taking so long. Just checked your code and tested it. Works fine. I added documentation. Release is on the way...

**Pull request merged**
